wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.40.0.dev0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712448003.0
    t:
      1:
      - 1
      - 11
      - 12
      - 49
      - 51
      - 55
      - 71
      - 98
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      3:
      - 7
      - 23
      4: 3.10.12
      5: 0.16.6
      6: 4.40.0.dev0
      8:
      - 1
      - 5
      - 12
      9:
        1: transformers_trainer
      13: linux-x86_64
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/grad_norm
      5: 1
      6:
      - 1
    - 1: train/learning_rate
      5: 1
      6:
      - 1
    - 1: train/epoch
      5: 1
      6:
      - 1
