wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: huggingface
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713751357.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 12
      - 49
      - 51
      - 55
      - 71
      - 98
      3:
      - 19
      - 23
      4: 3.10.12
      5: 0.16.6
      8:
      - 1
      - 5
      - 12
      13: linux-x86_64
TRAIN_BATCH_SIZE:
  desc: null
  value: 100
VALID_BATCH_SIZE:
  desc: null
  value: 100
TRAIN_EPOCHS:
  desc: null
  value: 10
VAL_EPOCHS:
  desc: null
  value: 10
LEARNING_RATE:
  desc: null
  value: 0.0001
SEED:
  desc: null
  value: 42
